// surveyjs-angular-poc/src/app/components/form-renderer/form-renderer.component.ts
import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router } from '@angular/router';
import { FormService, FormSchema } from '../../services/form.service';
import * as Survey from 'survey-core';

@Component({
  selector: 'app-form-renderer',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './form-renderer.component.html',
  styleUrls: ['./form-renderer.component.scss']
})
export class FormRendererComponent implements OnInit {
  @ViewChild('surveyContainer', { static: false }) surveyContainer?: ElementRef;

  formId: string | null = null;
  formSchema: FormSchema | null = null;
  isLoading = false;
  error: string | null = null;
  isSubmitted = false;
  submittedData: any = null;

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private formService: FormService
  ) {}

  ngOnInit(): void {
    this.route.queryParams.subscribe(params => {
      this.formId = params['id'] || null;
      if (this.formId) {
        this.loadForm(this.formId);
      }
    });
  }

  loadForm(id: string): void {
    this.isLoading = true;
    this.error = null;

    this.formService.getFormById(id).subscribe({
      next: (schema) => {
        this.formSchema = schema;
        this.isLoading = false;
        this.initializeSurvey(schema);
      },
      error: (err) => {
        this.error = `Failed to load form: ${err.message}`;
        this.isLoading = false;
        console.error('Error loading form:', err);
      }
    });
  }

  initializeSurvey(schema: FormSchema): void {
    if (!this.surveyContainer) {
      return;
    }

    const currentLocale = this.formService.getCurrentLocale();

    // Create survey model
    const survey = new Survey.Model(schema);

    // Set current language
    if (currentLocale !== 'default') {
      survey.locale = currentLocale;
    }

    // Handle survey completion
    survey.onComplete.add((result: any) => {
      this.handleFormSubmission(result);
    });

    // Render survey
    const container = this.surveyContainer.nativeElement;
    container.innerHTML = '';
    survey.render(container);
  }

  handleFormSubmission(result: any): void {
    this.submittedData = result.data;
    this.isSubmitted = true;

    if (this.formId) {
      this.formService.submitForm(this.formId, result.data).subscribe({
        next: (response) => {
          console.log('Form submission successful:', response);
        },
        error: (err) => {
          console.error('Form submission failed:', err);
        }
      });
    }
  }

  goBack(): void {
    this.router.navigate(['/']);
  }

  startOver(): void {
    this.isSubmitted = false;
    this.submittedData = null;
    if (this.formId) {
      this.loadForm(this.formId);
    }
  }
}

<div class="form-renderer-container">
  <div class="form-header">
    <button class="btn-back" (click)="goBack()">← Back to Forms</button>
    <h1 *ngIf="formSchema" class="form-title">
      {{ formService.getTranslation(formSchema.title) }}
    </h1>
  </div>

  <div *ngIf="isLoading" class="loading-spinner">
    <div class="spinner"></div>
    <p>Loading form...</p>
  </div>

  <div *ngIf="error" class="error-message">
    <span class="error-icon">⚠️</span>
    {{ error }}
  </div>

  <div *ngIf="!isLoading && !error && !isSubmitted" class="form-wrapper">
    <div #surveyContainer class="survey-container"></div>
  </div>

  <div *ngIf="isSubmitted" class="success-message">
    <div class="success-content">
      <span class="success-icon">✓</span>
      <h2>Form Submitted Successfully!</h2>
      <p>Thank you for completing the form. Your information has been recorded.</p>

      <div class="submitted-data">
        <h3>Submitted Data:</h3>
        <pre>{{ submittedData | json }}</pre>
      </div>

      <div class="button-group">
        <button class="btn btn-primary" (click)="startOver()">Fill Another Form</button>
        <button class="btn btn-secondary" (click)="goBack()">Back to Forms</button>
      </div>
    </div>
  </div>
</div>

// surveyjs-react-poc/src/components/FormRenderer/FormRenderer.jsx
import React, { useEffect, useRef } from 'react';
import { useSearchParams, useNavigate } from 'react-router-dom';
import { Survey } from 'survey-react-ui';
import 'survey-core/defaultV2.min.css';
import { useFormLoader } from '../../hooks/useFormLoader';
import { useFormSubmission } from '../../hooks/useFormSubmission';
import { useLocale } from '../../hooks/useLocale';
import { formService } from '../../services/formService';
import styles from './FormRenderer.module.css';

export const FormRenderer = () => {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const formId = searchParams.get('id');

  const { form, isLoading, error } = useFormLoader(formId);
  const { submitForm, isSubmitting, submittedData, clearSubmittedData } = useFormSubmission();
  const { getTranslation } = useLocale();
  const surveyRef = useRef(null);

  useEffect(() => {
    if (form) {
      // Create survey model
      const survey = new Survey.Model(form);

      // Set current language
      const currentLocale = formService.getCurrentLocale();
      if (currentLocale !== 'default') {
        survey.locale = currentLocale;
      }

      // Handle survey completion
      survey.onComplete.add((result) => {
        handleFormSubmission(result);
      });

      // Render survey
      survey.render(surveyRef.current);
    }
  }, [form]);

  const handleFormSubmission = (result) => {
    if (formId) {
      submitForm(formId, result.data);
    }
  };

  const handleStartOver = () => {
    clearSubmittedData();
    if (formId) {
      // Reload the form
      window.location.reload();
    }
  };

  const handleGoBack = () => {
    navigate('/');
  };

  return (
    <div className={styles.container}>
      <div className={styles.header}>
        <button className={styles.btnBack} onClick={handleGoBack}>
          ← Back to Forms
        </button>
        {form && (
          <h1 className={styles.title}>
            {getTranslation(form.title)}
          </h1>
        )}
      </div>

      {isLoading && (
        <div className={styles.loadingSpinner}>
          <div className={styles.spinner}></div>
          <p>Loading form...</p>
        </div>
      )}

      {error && (
        <div className={styles.errorMessage}>
          <span className={styles.errorIcon}>⚠️</span>
          {error}
        </div>
      )}

      {!isLoading && !error && !submittedData && (
        <div className={styles.formWrapper}>
          <div ref={surveyRef} className={styles.surveyContainer}></div>
        </div>
      )}

      {submittedData && (
        <div className={styles.successMessage}>
          <div className={styles.successContent}>
            <span className={styles.successIcon}>✓</span>
            <h2>Form Submitted Successfully!</h2>
            <p>Thank you for completing the form. Your information has been recorded.</p>

            <div className={styles.submittedData}>
              <h3>Submitted Data:</h3>
              <pre>{JSON.stringify(submittedData.data, null, 2)}</pre>
            </div>

            <div className={styles.buttonGroup}>
              <button className={`${styles.btn} ${styles.btnPrimary}`} onClick={handleStartOver}>
                Fill Another Form
              </button>
              <button className={`${styles.btn} ${styles.btnSecondary}`} onClick={handleGoBack}>
                Back to Forms
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default FormRenderer;
