// surveyjs-angular-poc/src/app/components/form-list/form-list.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { FormService, FormListItem } from '../../services/form.service';

@Component({
  selector: 'app-form-list',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './form-list.component.html',
  styleUrls: ['./form-list.component.scss']
})
export class FormListComponent implements OnInit {
  forms: FormListItem[] = [];
  currentLocale: string = 'default';
  isLoading = false;
  availableLocales = [
    { code: 'default', label: 'English' },
    { code: 'vi', label: 'Tiếng Việt' }
  ];

  constructor(
    private formService: FormService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.loadForms();
    this.formService.currentLocale$.subscribe(locale => {
      this.currentLocale = locale;
    });
  }

  loadForms(): void {
    this.isLoading = true;
    this.formService.getFormsList().subscribe({
      next: (forms) => {
        this.forms = forms;
        this.isLoading = false;
      },
      error: (err) => {
        console.error('Error loading forms:', err);
        this.isLoading = false;
      }
    });
  }

  switchLanguage(locale: string): void {
    this.formService.setLocale(locale);
    this.currentLocale = locale;
  }

  getLocalizedTitle(form: FormListItem): string {
    return this.formService.getTranslation(form.title);
  }

  getLocalizedDescription(form: FormListItem): string {
    if (form.description) {
      return this.formService.getTranslation(form.description);
    }
    return '';
  }

  openForm(formId: string): void {
    this.router.navigate(['/form'], { queryParams: { id: formId } });
  }
}

<div class="form-list-container">
  <header class="app-header">
    <div class="header-content">
      <div class="logo-section">
        <h1 class="app-title">📋 Form Builder POC</h1>
        <p class="subtitle">SurveyJS with Angular</p>
      </div>
      <div class="language-switcher">
        <span class="label">Language:</span>
        <div class="locale-buttons">
          <button
            *ngFor="let locale of availableLocales"
            [class.active]="currentLocale === locale.code"
            (click)="switchLanguage(locale.code)"
            class="locale-btn"
          >
            {{ locale.label }}
          </button>
        </div>
      </div>
    </div>
  </header>

  <main class="main-content">
    <div class="forms-container">
      <h2 class="section-title">
        {{ currentLocale === 'vi' ? 'Danh sách biểu mẫu' : 'Available Forms' }}
      </h2>

      <div *ngIf="isLoading" class="loading-message">
        <div class="spinner"></div>
        <p>{{ currentLocale === 'vi' ? 'Đang tải...' : 'Loading...' }}</p>
      </div>

      <div *ngIf="!isLoading && forms.length === 0" class="empty-message">
        <p>{{ currentLocale === 'vi' ? 'Không có biểu mẫu nào' : 'No forms available' }}</p>
      </div>

      <div *ngIf="!isLoading && forms.length > 0" class="forms-grid">
        <div
          *ngFor="let form of forms"
          class="form-card"
          (click)="openForm(form.id)"
        >
          <div class="card-header">
            <span class="form-icon">📝</span>
            <h3 class="form-title">{{ getLocalizedTitle(form) }}</h3>
          </div>
          <p class="form-description">{{ getLocalizedDescription(form) }}</p>
          <div class="card-footer">
            <button class="btn-open">
              {{ currentLocale === 'vi' ? 'Mở biểu mẫu' : 'Open Form' }} →
            </button>
          </div>
        </div>
      </div>
    </div>
  </main>

  <footer class="app-footer">
    <p>
      {{ currentLocale === 'vi'
        ? 'Hệ thống xây dựng biểu mẫu động với SurveyJS và Angular'
        : 'Dynamic Form Builder System with SurveyJS and Angular' }}
    </p>
  </footer>
</div>

// surveyjs-react-poc/src/components/FormList/FormList.jsx
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { formService } from '../../services/formService';
import { useLocale } from '../../hooks/useLocale';
import styles from './FormList.module.css';

export const FormList = () => {
  const navigate = useNavigate();
  const [forms, setForms] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const { locale, setLocale, getTranslation } = useLocale();

  const availableLocales = [
    { code: 'default', label: 'English' },
    { code: 'vi', label: 'Tiếng Việt' }
  ];

  useEffect(() => {
    loadForms();
  }, []);

  const loadForms = async () => {
    setIsLoading(true);
    try {
      const formsList = await formService.getFormsList();
      setForms(formsList);
    } catch (error) {
      console.error('Error loading forms:', error);
    }
    setIsLoading(false);
  };

  const handleOpenForm = (formId) => {
    navigate(`/form?id=${formId}`);
  };

  const handleSwitchLanguage = (localeCode) => {
    setLocale(localeCode);
  };

  return (
    <div className={styles.container}>
      <header className={styles.header}>
        <div className={styles.headerContent}>
          <div className={styles.logoSection}>
            <h1 className={styles.appTitle}>📋 Form Builder POC</h1>
            <p className={styles.subtitle}>SurveyJS with React</p>
          </div>
          <div className={styles.languageSwitcher}>
            <span className={styles.label}>Language:</span>
            <div className={styles.localeButtons}>
              {availableLocales.map(localeItem => (
                <button
                  key={localeItem.code}
                  className={`${styles.localeBtn} ${locale === localeItem.code ? styles.active : ''}`}
                  onClick={() => handleSwitchLanguage(localeItem.code)}
                >
                  {localeItem.label}
                </button>
              ))}
            </div>
          </div>
        </div>
      </header>

      <main className={styles.mainContent}>
        <div className={styles.formsContainer}>
          <h2 className={styles.sectionTitle}>
            {locale === 'vi' ? 'Danh sách biểu mẫu' : 'Available Forms'}
          </h2>

          {isLoading && (
            <div className={styles.loadingMessage}>
              <div className={styles.spinner}></div>
              <p>{locale === 'vi' ? 'Đang tải...' : 'Loading...'}</p>
            </div>
          )}

          {!isLoading && forms.length === 0 && (
            <div className={styles.emptyMessage}>
              <p>{locale === 'vi' ? 'Không có biểu mẫu nào' : 'No forms available'}</p>
            </div>
          )}

          {!isLoading && forms.length > 0 && (
            <div className={styles.formsGrid}>
              {forms.map(form => (
                <div
                  key={form.id}
                  className={styles.formCard}
                  onClick={() => handleOpenForm(form.id)}
                >
                  <div className={styles.cardHeader}>
                    <span className={styles.formIcon}>📝</span>
                    <h3 className={styles.formTitle}>{getTranslation(form.title)}</h3>
                  </div>
                  <p className={styles.formDescription}>
                    {form.description ? getTranslation(form.description) : ''}
                  </p>
                  <div className={styles.cardFooter}>
                    <button className={styles.btnOpen}>
                      {locale === 'vi' ? 'Mở biểu mẫu' : 'Open Form'} →
                    </button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </main>

      <footer className={styles.footer}>
        <p>
          {locale === 'vi'
            ? 'Hệ thống xây dựng biểu mẫu động với SurveyJS và React'
            : 'Dynamic Form Builder System with SurveyJS and React'}
        </p>
      </footer>
    </div>
  );
};

export default FormList;
